### PR TITLE
Add GitHub CI

### PR DESCRIPTION
**Pull request by J0WI**
Once the tests have been [moved upstream](https://github.com/docker-library/official-images/tree/master/test/tests) we can finally remove Travis.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
LGTM, let me know when I can merge

**Comment by J0WI** [comment]
You can merge this already and Travis can be removed once https://github.com/docker-library/official-images/pull/9046 is merged.

**Comment by williamdes** [comment]
Merged :rocket: 
GHA was enabled but I could not know before merging
https://github.com/phpmyadmin/docker/actions/runs/445396186 :green_circle: 

Can you help me remove TravisCI because I am not sure all the tests are implemented into GitHub actions

**Comment by J0WI** [comment]
> Can you help me remove TravisCI because I am not sure all the tests are implemented into GitHub actions

My goal is to merge the tests in https://github.com/docker-library/official-images/pull/9046. The current test setup might be a bit [too bloated](https://github.com/docker-library/official-images/pull/9046#issuecomment-724359673). A minimal test case or smoke test would already be sufficient.

**Comment by williamdes** [comment]
> > Can you help me remove TravisCI because I am not sure all the tests are implemented into GitHub actions
> 
> My goal is to merge the tests in [docker-library/official-images#9046](https://github.com/docker-library/official-images/pull/9046). The current test setup might be a bit [too bloated](https://github.com/docker-library/official-images/pull/9046#issuecomment-724359673). A minimal test case or smoke test would already be sufficient.

Okay, great idea! 
I like minimal and clear things

**Pull request merged**
