### PR TITLE
Fix #133 - Add `TZ` env var to change PHP `date.timezone`

### LINKED ISSUE #133: Unable to change timezone
I cannot change the timezone inside the docker. the TZ variable is ignored and the typical files for setting the timezone is also ignored /etc/timezone and /etc/localtime

Its set to UTC as per default, but as i live en the Europe/Copenhagen timezone, its two hours offset.

How do i change that?

### PR DESCRIPTION
**Pull request by Sergio-IME**
this allows date pickers in UI to pick up the right time

Fixes: #133

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you, it looks good
I will probably merge this when 5.2.1 is released

**Comment by williamdes** [comment]
> Thank you, it looks good I will probably merge this when 5.2.1 is released

Well, I missed it. But it can make it to 5.2.1. Will let you know here

**Comment by williamdes** [comment]
Pending deployment !
:tada:

See: https://github.com/docker-library/official-images/pull/14347

it should hit the hub in the day or tomorrow

**Comment by Sergio-IME** [comment]
yay 🎉 
Thank you

**Pull request merged**
