### PR TITLE
Add expose_php env back

### PR DESCRIPTION
**Pull request by J0WI**
https://github.com/docker-library/official-images/pull/9426#issuecomment-771834823

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you !

**Comment by williamdes** [comment]
Maybe you will have to adjust the env value in the test docker compose files :thinking: 
https://github.com/phpmyadmin/docker/pull/324/checks?check_run_id=1849422048#step:4:235

**Comment by J0WI** [comment]
`HIDE_PHP_VERSION=1` turns into `expose_php=1` which means the opposite.

**Comment by williamdes** [comment]
> `HIDE_PHP_VERSION=1` turns into `expose_php=1` which means the opposite. There's no simple way for the current documented behaviour to just relay on php.ini env substitution.

Oh, I see
Maybe you can add back the script block and adjust the test so it tests the opposite of the parent docker image config

**Review by williamdes — APPROVED** [review]

**Pull request merged**
