### PR TITLE
concatenate Dockerfile commands - reduces final images size

### PR DESCRIPTION
**Pull request by CybotTM**
Hi,

this patch reduces final image size from 99 MiB to 57 MiB

### CODE REVIEW

**Comment by nijel** [comment]
Merged thanks. Can you please point me to some docs, why this makes the difference?

**Comment by CybotTM** [comment]
The reason is the layered file system and how docker builds/processes the Dockerfile.
I'm not sure if their is documentation that describes this effect exactly - but if you understand the layered FS and how docker builds the images you will come to this conclusion by yourself.
It's just a current best practice.

- http://woudenberg.io/reducing-docker-image-size/
- https://labs.ctl.io/optimizing-docker-images/

**Comment by nijel** [comment]
Thanks for the links!

**Comment by lem9** [comment]
@CybotTM Hi Sebastian, happy to see you again!

**Pull request merged**
