### PR TITLE
Increase limits for upload and post

### PR DESCRIPTION
**Pull request by williamdes**
Ref: #238
Closes: #240
Closes: #239
Closes: #233
Closes: #189

### CODE REVIEW

**Comment by williamdes** [comment]
@J0WI does this tick another box on https://github.com/phpmyadmin/docker/issues/56#issuecomment-394519670

**Comment by J0WI** [comment]
I forgot to update the checklist. This reverts #221, see also https://github.com/docker-library/wordpress/issues/10

**Comment by williamdes** [comment]
I did not understand if removing the custom limit was intentional or not ?

**Comment by J0WI** [comment]
It was intentional. The task in the checklist was 

> default values like the upload limit should **not** be changed

**Comment by williamdes** [comment]
Okay, so what should we do for unhappy users uploading big files that are using the docker image ?

**Comment by J0WI** [comment]
I'd just merge #238. This setting is not [required](https://docs.phpmyadmin.net/en/latest/require.html#php), so if I haven't configured anything myself I'd expect the default value.

**Comment by williamdes** [comment]
Maybe adding an ENV variable for the upload limit would avoid users having to try to change the configuration ?

**Comment by J0WI** [comment]
Yes, I think `.htaccess` or `.user.ini` would work too.

**Comment by drexlma** [comment]
i need this!!!

**Comment by williamdes** [comment]
I did a mistake and pushed wrong version of master, reverted in 5f2beb027aa73222cf983d88ebe28811cb3846bb

**Pull request merged**
