### PR TITLE
Upgrade to Alpine 3.5

### LINKED ISSUE #34: Any reason not to update this to use PHP 7?
I'm using PHP 7 everywhere now and am curious if there's a reason not to update this package.

Thanks,

S

### PR DESCRIPTION
**Pull request by nijel**
Also switch to PHP 7

Fixes #34

Signed-off-by: Michal Čihař <michal@cihar.com>

### CODE REVIEW

**Comment by nijel** [comment]
Depends on new Alpine image, see https://github.com/gliderlabs/docker-alpine/issues/235

**Comment by amelialandyn** [comment]
Nice[.](http://www.forskolinfuel-reviews.com)this actually workks

**Comment by Anna978** [comment]
Interesting post. I
Have Been wondering about this issue, so thanks for posting.
 [url=http://calculatorbmi.org/] bmi calculator [/url]

**Comment by Anna978** [comment]
Thanks so much for this wonderful and great website as well as this post.
[bmi calculator](http://calculatorbmi.org)

**Pull request merged**
