### PR TITLE
Add PMA_QUERYHISTORYMAX config parameter

### PR DESCRIPTION
**Pull request by sadortun**

### CODE REVIEW

**Comment by ibennetch** [comment]
Thank you for your submission.

This is a slippery slope because I feel it's not really in the best interest to implement every configuration option as a Docker command line argument. At some point, one has to actually use a configuration file rather than passing a long string of arguments.

I would vote no on this, but wonder what others think.

**Comment by sadortun** [comment]
@ibennetch If contributors want to submit PR to improve configurability, i dont see how its a problem :) Also, you could do the same as for `PMA_QUERYHISTORYDB` and not mention it in the docs. But still useful if users want to adjust it.

Alternatively, you could provide a simple syntax parser that would rewrite ENV to appropriate config parameters. That way, Everything could be configurable via ENV.

**Comment by williamdes** [comment]
> Thank you for your submission.
> 
> This is a slippery slope because I feel it's not really in the best interest to implement every configuration option as a Docker command line argument. At some point, one has to actually use a configuration file rather than passing a long string of arguments.
> 
> I would vote no on this, but wonder what others think.

I would say yes because the option for query history db exists. 
And no because of the bad idea that it is to have all our config options as hard coded ENVs

So for me I think we need to find a better solution for that and use QA_5_0 for the feature. 
- support existing ENVs
- add a cool system to manage all config options

**Comment by sadortun** [comment]
Did not want to trigger a mid-life existantial crisis :) Only wanted to add my `history max size` param :) hehehhe

**Comment by sadortun** [comment]
@ibennetch Could you please merge this ? It doesn't prevent you to refactored the feature when you reach a decision, or postpone that decision making until someone else want to add another param 🙏

**Review by williamdes — APPROVED** [review]
Merging this only because PMA_QUERYHISTORYDB is present 

Thank you for your contribution (and patience) !

**Pull request merged**
