### PR TITLE
Fetch GnuPG key from keyserver 

### PR DESCRIPTION
**Pull request by J0WI**
Notes:
* Fetching the key from a keyserver make sure that changes (e.g. revocation) are applied
* This also removes the keyring binary from this repo
* Code style is now more consistent
* Moving the installation of required software on top may speed up installation of other dependencies (if they share some) and caches this step

### CODE REVIEW

**Comment by J0WI** [comment]
@nijel can I get some feedback on this?

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by nijel** [comment]
Apparently it's not the most reliable keyserver: `gpg: keyserver receive failed: Address not available`, see https://travis-ci.org/phpmyadmin/docker/jobs/367994869#L1737

**Comment by nijel** [comment]
I've tried to use different keyserver, but I'm not really sure relying on external service here was a good idea. People end up doing workaround like in https://github.com/nodejs/docker-node/issues/380#issuecomment-348464695

**Comment by J0WI** [comment]
That's a common issue: https://github.com/docker-library/postgres/issues/262#issuecomment-279570514

**Comment by J0WI** [comment]
@nijel how about using `travis_retry` instead of 2fe59471167915cd09de043d901b5e59c3b50ade?

**Comment by nijel** [comment]
`travis_retry` will not help in case there is some issue on the network (eg. the ivp4/ipv6 issue mentioned above), that's why I've decided to try different keyservers instead.

**Pull request merged**
