### PR TITLE
Update to PHP 7.4

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by williamdes** [comment]
@J0WI can you do the upgrade to 7.4 to fix #258 ?

cc @ibennetch

**Comment by J0WI** [comment]
Done

**Comment by ibennetch** [comment]
Looks good to me. Thank you for this.

Soon I can release 4.9.2-2 to include this patch and and #259.

**Comment by fruitl00p** [comment]
Any timeline for getting the official images updated to 7.4?

**Comment by ibennetch** [comment]
Robin, probably this weekend, at least I hope so. I may get to updating
'master' tonight.

I'm a little unsure if I should release Docker tags like 4.9.2-2 for this
or if users will pull by digest (see
https://github.com/phpmyadmin/docker/pull/259#discussion_r357939102 and
feel free to comment if you have any input).

**Comment by fruitl00p** [comment]
i personally have never seen any pulling by digest in the wild by users...
anyway, looking forward to a 7.4 release... But could also wait for a
normal version tag to achieve that new crispy 7.4 feeling 😀

Op do 19 dec. 2019 20:27 schreef Isaac Bennetch <notifications@github.com>:

**Comment by ibennetch** [comment]
I've merged this change and pushed a new Docker tag so 7.4 should be building now for all the current Docker tags. There's even a `4.9.2-2` tag for this.

@J0WI thank you for doing this work.

**Pull request merged**
